### ISSUE TITLE
ssues of sending out multiple messages using MSRP Java library

### ISSUE THREAD

**Issue by stevesui** [MSRP-OSS/msrp-java#1]
I have been trying to send multiple messages using the MSRP Java example "UsingLibraryByTwoNetworkEndpoints.java" that comes with the package.  The problem was only first message got sent. The rest of messages seemed to be lost.

I have the both manual sender and manual receiver running properly after two parties exchanged their endpoint URIs.

After connections were established, I tried to send multiple messages by using the helper function MessageSender.generateRandomMemoryMessage(3000) multiple times, expecting manual receiver will display multiple messages. However, the manual sender only send out the first message. The rest of messages were never sent.  On manual receiver side, I only see the first message. 

I traced into the code and found out that inside Session class, the method "OutgoingMessage sendMessage(OutgoingMessage message)" actually stored the messages into an ArrayList variable named sendQueue. Session.triggerSending method checks if there are any more messages in the sendQueue, if there is it will pop them out and send over the network using Connection class. The wired thing that I found is that after the first message is popped out, the sendQueue "lost" all other messages previously stored there. I could not figure out how other messages were drained.

Below is the code of the manual sender from the example. The only thing I changed is to add a for loop to send multiple messages after the connection established. But, as I noted above, only first message got sent. Other messages were not sent. 

I really appreciate for any help on how to make manual sender to  send out multiple messages after connection is established.

location: src/main/java/javax.net.msrp.examples/UsingLibraryByTwoNetworkEndpoints.java

....
 case 2:
            if (args[0].compareToIgnoreCase("manual") != 0 ||
                args[1].compareToIgnoreCase("sender") != 0)
                parameterError();
            else
            {
                try
                {
                    /*
                     * "manual" sender mode, just generate the message and URI
                     * and wait the URI that should come when the receiving end
                     * is run with the generated URI from this sender, after
                     * that it connects to the receiver
                     */
                    @SuppressWarnings("unused")
					URI senderUri = MessageSender.setUpConnection();

                    /* prompt and get the uri from the standard input: */
                    System.out.print(
                    		"Please input the sender's one-URI to-path (the receiver URI that was generated by the program in the receiver mode):");
                    BufferedReader br =
                        new BufferedReader(new InputStreamReader(System.in));
                    String uriString;
                    uriString = br.readLine();
                    /*
                     * create the needed URI ArrayList and add the URI that was
                     * given via the standard input:
                     */
                    ArrayList<URI> toPathSendSession = new ArrayList<URI>();
                    URI toPathUri = URI.create(uriString);
                    toPathSendSession.add(toPathUri);
                    /*
                     * add it to the sendingSession's toPath (connecting the two
                     * end-points and starting the message transfer):
                     */
                    MessageSender.sendingSession.setToPath(toPathSendSession);
                   
/*
The following is the code I added. It loops 10 times. But only the first message was sent
*/
                  for (int i = 0; i<10; i++)
                    MessageSender.generateRandomMemoryMessage(3000);
     
                }
                catch (Exception e)
                {
                    System.out
                        .println("An exception occurred in the sender in the manual mode:");
                    e.printStackTrace();
                    System.exit(ERROR);
                }
            }
            break;

Thanks a lot.

Steve Sui

**Comment by tuijldert** [comment]
Not heard anything from Joao yet so I'll have a quick stab at it:
The main code only provides for the reception of 1 message on the receivingSessionListener.
So if you want to receive the rest, you'll have to build a loop that reads more messages.

**Comment by joantune** [comment]
It's been a while.. last time I touched this the US was electing a non racist and actually a black president for the first time... back to the issue at hands:

~~@stevesui: it's been too long.. probably @tuijldert  is right.. can you make a watch breakpoint in that arraylist? that way you know who empties it..~~

@stevesui : @tuijldert is right. The receiving session listener only shows the last message sent. You need to either change the listener to allow him to get several messages, or you need to make another listener everytime you need to send a message.

msrp-java/src/main/java/javax/net/msrp/testutils/MockSessionListener.java - line 113

besides having an awkward handling of threads and a some kinda messy code (it's good to know that I came a long way since then), you can also see that the 'data container' gets reused everytime.

By the way, since that there are threads involved, to find out who is doing things in this case:

> The wired thing that I found is that after the first message is popped out, the sendQueue "lost" all other messages previously stored there. I could not figure out how other messages were drained.

you can and should make a watch breakpoint on that variable.
