### ISSUE TITLE
About sending files and setChunkSize not 0

### ISSUE THREAD

**Issue by ljs528** [MSRP-OSS/msrp-java#17]
When I use FileDataContainer to send a file to another place, there will be a parsing error if setChunkSize is not set to 0, but I have a requirement that the size of Chunk needs to be set manually, how can I solve it

**Comment by ljs528** [comment]
I use JDK1.8 and MSRP's latest maven dependency
`senderSession.setChunkSize(2048);
File file = new File("D:\\BaiduNetdiskDownload\\javaweb source.zip");
                            ArrayList<URI> uris = new ArrayList<URI>();
                            uris.add(peerMsrpUri);
                            senderSession.sendMessage(TEXT_TYPE,file);
                            senderSession.setToPath(uris);`

**Comment by ljs528** [comment]
I use JDK1.8 and MSRP's laster maven dependency.
Like this,

`senderSession.setChunkSize(2048);`
`File file = new File("D:\\BaiduNetdiskDownload\\javaweb source.zip");`
 `ArrayList<URI> uris = new ArrayList<URI>();`
 `uris.add(peerMsrpUri);`
`senderSession.sendMessage(TEXT_TYPE,file);`
 `senderSession.setToPath(uris);`

This is a piece of code to send, I want to send a 10M file, but setChunkSize(2048) will make an error, after the number is not necessarily 2048 but there is a threshold value, I have tested several files, did not find any rule, this 10M file only when I set 1024*243 line.

This is the exception when set to 2048
`javax.net.msrp.exceptions.ParseException: Error, start of the transaction not found on thread: Connection: msrp://172.18.178.241:61483 readThread`
`at javax.net.msrp.Connection.parser(Connection.java:672)`
`at javax.net.msrp.PreParser.preParse(PreParser.java:248)`
`at javax.net.msrp.Connection.readCycle(Connection.java:430)`
`at javax.net.msrp.Connection.run(Connection.java:479)`
`at java.lang.Thread.run(Thread.java:748)`

![image](https://user-images.githubusercontent.com/41655351/52097768-48d42500-2607-11e9-94f4-4737617dc223.png)
When I went to check the source code, I found that what was wrong was the section of the Connection class parser method. In this do while loop, the character string extracted from the txRest set was broken in the second loop, and neither of the next two regular expressions was true, thus throwing an exception

Is there a balance between chunSize? Different files need to be set to different sizes

**Comment by ljs528** [comment]
I actually want to deal with a breakpoint to continue downloading the file,The first thing that comes to mind is message chunking, and I don't know if there are any other ideas to implement it

**Comment by tuijldert** [comment]
Sorry for the late reply, haven't had time to look see yet.
Hope to spend some time on this before the week-end.
Cheers,
    Tom.

**Comment by ljs528** [comment]
Thank you very much for taking the time to help me find out the problem,This problem may be the problem of the sender, if the block size is not appropriate, the receiver will print the received message and find that part of the message is missing, like this
![image](https://user-images.githubusercontent.com/41655351/52542771-2e0b6880-2dde-11e9-963e-8068eac52bbe.png)
![image](https://user-images.githubusercontent.com/41655351/52542836-da4d4f00-2dde-11e9-87e7-79753ab3fb07.png)
Print ends with ------<<<<< <
A normal message looks like this
![image](https://user-images.githubusercontent.com/41655351/52542798-6ad75f80-2dde-11e9-8772-e83b0956faf0.png)

**Comment by ljs528** [comment]
This problem has been solved, but it doesn't feel too strict.
I added two if's on TransactionManager class getDataToSend method.
The problem is that after reading the terminator ------ - id $,There is not enough space left to read the header of the next block, but there is no judgment at there,so A situation occurred where  the (MSRP id SE) was read,So after I read the terminator to determine whether the position is enough, if not , jump out.

**Comment by tuijldert** [comment]
Hi,
Thanks for your contribution but now I think we're muddying the waters here.
The first was definitely a chunking bug, but what you're describing last is an inevitable consequence of chunking.
Your "solution" wouldn't work here either, given that 233 bytes is fairly arbitrary: any longer URI's in your header and your implementation would break...

So, I suggest you open a new issue for this.
Also, I'm not entirely clear on what you are trying to solve here/what the actual problem is.
Could you maybe elaborate a bit?

Thanks,
   Tom.

**Comment by ljs528** [comment]
sorry,I just wanted to use this framework to make a file2file mode and support breakpoint continuation download, so I thought of the chunk here, but encountered these errors when using the chunk.

**Comment by tuijldert** [comment]
Fair enough, problem becomes clearer now.
That's what the (`File`-)`DataContainer` class is for.
I'd suggest implementing your own `FileDataContainer` subclass that handles breakpoints and using that to insert into `Message.setDataContainer()`.

Good luck on that and thanks for your contribution.
